FuelLabs/fuel.nix

flake.nix, patches.nix
@Voxelot @freesig here we go, definitely speeds up the `fuel-core` build quite a bit locally, and slims the binary size by about a third!
Here are the changes I'm seeing with `fuel-core` `0.10.1`:
**Before**
```
$ ldd ./result/bin/fuel-core
linux-vdso.so.1 (0x00007ffe3e3eb000)
libstdc++.so.6 => /nix/store/k2a429wpxgfwp4jaacl9iaqw4kxqjaxa-gcc-11.3.0-lib/lib/libstdc++.so.6 (0x00007f20236ed000)
libgcc_s.so.1 => /nix/store/7fz6dhhriwv6n4kdg05qi8cwf7mfqza9-glibc-2.35-163/lib/libgcc_s.so.1 (0x00007f20236d3000)
libm.so.6 => /nix/store/7fz6dhhriwv6n4kdg05qi8cwf7mfqza9-glibc-2.35-163/lib/libm.so.6 (0x00007f20235f3000)
libc.so.6 => /nix/store/7fz6dhhriwv6n4kdg05qi8cwf7mfqza9-glibc-2.35-163/lib/libc.so.6 (0x00007f20233e9000)
/nix/store/7fz6dhhriwv6n4kdg05qi8cwf7mfqza9-glibc-2.35-163/lib/ld-linux-x86- …
```
=> Dynamically link to precompiled `rocksdb` from `fuel-core`

README.md
After helping @voxelot work out why Nix was trying to build perl from scratch on Ubuntu, I realised we need to make sure we also include the standard nixos cache in the `nix.conf`.
I've also added a note for non-NixOS Linux users about ensuring their user is in the `nixbld` group to ensure they have permissions to use the remote caches to populate the local `/nix/store`.
=> Update the README with instructions for adding the nixos cache

flake.lock, patches.nix
This should account for https://github.com/FuelLabs/fuel-core/commit/bcb86da09b6fdce09f13ef4181a0ca6461f8e2a8 while still allowing to use 1.63 (and in turn, already cached builds) for prior versions.
=> Update the version of Rust used to 1.64 for all pkgs after 2022-09-23

flake.nix
Previously, the devShells provided the build inputs and environment from the latest *semver* release of their respective packages. This meant that the devShells could fall behind the current development requirements.
This changes the devShells to instead provide the build environment of their respective *nightly* packages, ensuring that the devShells are at least up-to-date within 24 hrs.
Issue previously spotted [here](https://github.com/FuelLabs/fuel.nix/pull/23#issuecomment-1256554688).
=> Use nightly package build inputs to ensure devShells have up-to-date tools

flake.lock
It looks like my previous rust-overlay update in #23 was a little early and didn't include 1.64 yet. #23 didn't show any issues yet as none of the packages at the time of that commit were released after 2022-09-23, and so we didn't hit the error until the latest nightlies merged into `master` with #27 which also didn't show any issues as it was was opened before #23 was merged :')
This should fix it! It's probably worth enabling the same branch protection we have on the Sway repo where merging a PR requires it's up to date with `master` to avoid cases like this.
=> Update rust-overlay input for latest Rust stable 1.64 release

.github/workflows/ci.yml, .github/workflows/refresh-manifests.yml, flake.nix
No commits have been made to forc-explore since including adding it to the Nix flake - as a result, no nightly package has been made available. This makes the forc-explore-nightly inclusion optional and dependent on whether or not a nightly actually exists.
This slipped through as during CI we'd only build the packages, however the `devShell`s were never checked. This adds another job to the PR CI that checks the `fuel-dev` `devShell` on both macOS and Linux. Also adds a similar step to the refresh-manifests CI to catch any unexpected breakage there too.
Also closes #38.
=> Fix bug in `fuel-dev` due to `forc-explore-nightly` not yet being available. Check `nix develop` in CI.

manifests/forc-0.33.0-nightly-2023-01-14.nix, manifests/forc-client-0.33.0-nightly-2023-01-14.nix, manifests/forc-fmt-0.33.0-nightly-2023-01-14.nix, manifests/forc-lsp-0.33.0-nightly-2023-01-14.nix, manifests/fuel-core-0.14.2-nightly-2023-01-14.nix, manifests/fuel-core-client-0.14.2-nightly-2023-01-14.nix, patches.nix
Fixes the recent failure in the refresh-manifests job here: https://github.com/FuelLabs/fuel.nix/actions/runs/3915857625/jobs/6694412087#step:9:32. This PR also adds the manifests that didn't make it in.
=> Add missing input hash for new git ethabi dependency in sway workspace

flake.lock, manifests/forc-0.34.0-nightly-2023-02-04.nix, manifests/forc-client-0.34.0-nightly-2023-02-04.nix, manifests/forc-doc-0.34.0-nightly-2023-02-04.nix, manifests/forc-fmt-0.34.0-nightly-2023-02-04.nix, manifests/forc-index-0.2.2-nightly-2023-02-04.nix, manifests/forc-lsp-0.34.0-nightly-2023-02-04.nix, manifests/forc-tx-0.34.0-nightly-2023-02-04.nix, manifests/fuel-core-0.16.1-nightly-2023-02-04.nix, manifests/fuel-core-client-0.16.1-nightly-2023-02-04.nix, manifests/fuel-indexer-0.2.2-nightly-2023-02-04.nix, patches.nix
Updates the `rust-overlay` flake input to bring in support for 1.67.
Also udpates a fuel-core patch to ensure tests aren't run unnecessarily for new fuel-core-client crate.
Also includes manifests for previous failed CI job.
=> `fuel-core` now requires Rust 1.67

filters.nix, manifests/forc-0.35.3-nightly-2023-02-22.nix, manifests/forc-0.35.3.nix, manifests/forc-client-0.35.3-nightly-2023-02-22.nix, manifests/forc-client-0.35.3.nix, manifests/forc-doc-0.35.3-nightly-2023-02-22.nix, manifests/forc-doc-0.35.3.nix, manifests/forc-fmt-0.35.3-nightly-2023-02-22.nix, manifests/forc-fmt-0.35.3.nix, manifests/forc-index-0.3.0-nightly-2023-02-22.nix, manifests/forc-index-0.4.0.nix, manifests/forc-lsp-0.35.3-nightly-2023-02-22.nix, manifests/forc-lsp-0.35.3.nix, manifests/forc-tx-0.35.3-nightly-2023-02-22.nix, manifests/forc-tx-0.35.3.nix, manifests/forc-wallet-0.2.0-nightly-2023-02-22.nix, manifests/forc-wallet-0.2.1.nix, manifests/fuel-core-0.17.3-nightly-2023-02-22.nix, manifests/fuel-core-0.17.3.nix, manifests/fuel-core-client-0.17.3-nightly-2023-02-22.nix, manifests/fuel-core-client-0.17.3.nix, manifests/fuel-indexer-0.3.0-nightly-2023-02-22.nix, manifests/fuel-indexer-0.4.0.nix
Closes https://github.com/FuelLabs/fuel.nix/issues/53.
Refreshes manifests since the indexer build started failing.
=> Temporarily filter out indexer packages

.github/workflows/ci.yml, .github/workflows/refresh-manifests.yml, LICENSE
Looks like a recent version of Nix broke the nix-cachix-install action - hopefully this does the trick: https://github.com/cachix/install-nix-action/releases/tag/v20.
Edit: just noticed we were missing the license - I've copied the one we use for the rest of tooling from the Sway repo.
=> Attempt to fix github CI cachix workflow error

.github/workflows/refresh-manifests.yml
This job takes a while as it fetches all of the various fuel repos and scans git history for tags to generate the manifests in an idempotent manner, once for each package. One day we should update `scripts/refresh-manifests` to do a single traversal per-repo, not per pkg.
=> Increase timeout of `refresh-manifests` job

.github/workflows/ci.yml, .github/workflows/refresh-manifests.yml, README.md
This switches from the old `mitchmindtree-fuellabs` cachix cache to the new `fuellabs` one.
Updates both CI and the README installation instructions.
Note: This might take a while to build as we populate the cache for the first time!
=> Switch to the new fuellabs cachix cache

manifests/forc-0.39.1-nightly-2023-05-30.nix, manifests/forc-0.39.1-nightly-2023-05-31.nix, manifests/forc-client-0.39.1-nightly-2023-05-30.nix, manifests/forc-client-0.39.1-nightly-2023-05-31.nix, manifests/forc-doc-0.39.1-nightly-2023-05-30.nix, manifests/forc-doc-0.39.1-nightly-2023-05-31.nix, manifests/forc-fmt-0.39.1-nightly-2023-05-30.nix, manifests/forc-fmt-0.39.1-nightly-2023-05-31.nix, manifests/forc-index-0.15.1-nightly-2023-05-31.nix, manifests/forc-lsp-0.39.1-nightly-2023-05-30.nix, manifests/forc-lsp-0.39.1-nightly-2023-05-31.nix, manifests/forc-tx-0.39.1-nightly-2023-05-30.nix, manifests/forc-tx-0.39.1-nightly-2023-05-31.nix, manifests/fuel-core-0.18.1-nightly-2023-05-30.nix, manifests/fuel-core-client-0.18.1-nightly-2023-05-30.nix, manifests/fuel-indexer-0.15.1-nightly-2023-05-31.nix, patches.nix
Currently, the frameworks are provided as build inputs - this is an attempt to provide the CoreFoundation framework as a nativeBuildInput to see if it addresses the current CI error tracked in #64.
Edit: Also tried `propagatedBuildInputs` to see if propagating CoreFoundation to the runtime inputs helped, but no luck.
Edit: Now attempting to remove the most recent manifest sets in order to find the last working version of `fuel-nightly` so I can diff the two.
=> Attempt to solve `macos-latest` `x86_64-darwin` CI build issues for `fuel-nightly`

.github/workflows/ci.yml, .github/workflows/refresh-manifests.yml
Closes #70
Closes #71
The new workflow has three main jobs:
1. Refresh the manifests using the `refresh-manifests.sh` script and upload the `manifests` directory to temporary workflow storage.
2. If `1.` succeeds: For all supported platforms and all major package sets (fuel, fuel-nightly, fuel-beta-3, etc), download the new manifests from temporary storage, add them to git staging so they get picked up by nix, then do a test nix build. Cache the binaries on success.
3. If `2.` succeeds: Download the manifests from temporary storage, commit them to master and push to the main master branch.
=> refresh-manifests workflow checks all platforms before committing manifests

.github/workflows/publish-book.yml
Adds the missing nix installation that provides the environment for building the book.
Follow-up to #61
=> Fix fuel.nix book building step in publish-book workflow

flake.lock, patches.nix
Also updates the `rust-overlay` flake input in order to enable the new version.
=> Update rust version to 1.68, required by recent `forc-client` version

.github/workflows/ci.yml, .github/workflows/publish-book.yml, .github/workflows/refresh-manifests.yml
closes #80.
This PR gets the fix mentioned [here](https://github.com/cachix/install-nix-action/issues/183#issuecomment-1595162172). Fixes the CI so that following error is not blocking our macos runners:
```console
Could not set environment: 150: Operation not permitted while System Integrity Protection is engaged
Error: Process completed with exit code 150.
```
=> ci: bump install-nix-action to v22 to get upstream `macos` install fix (#81)

book/src/nix-setup.md
=> Add trouble shooting section to the book

book/src/quick-start.md
quick-start.md was linked to the previous notion-based documentation portal. 
This fix changes the link to the current documentation portal aka [docs-hub](https://docs.fuel.network/)
=> fix: docs portal link

.github/workflows/ci.yml, .github/workflows/refresh-manifests.yml, milestones.nix
Beta-4 is stable now and should be used instead. 
These were removed in fuelup here https://github.com/FuelLabs/fuelup/pull/511
=> chore: remove beta-4 rc channels

patches.nix
`fuel-tx` requires Rust 1.73 as of ~2023-11-29 due to use of `div_ceil`.
=> fix: bump MSRV to 1.73 from 2023-11-29

.github/workflows/ci.yml, .github/workflows/refresh-manifests.yml
Because they use a version of `librocksdb-sys` which is broken.
=> Don't build beta-1 and beta-2 on CI

book/src/quick-start.md
closes #108.
This PR changes quick start section in the book so that people would install latest beta network available if they blindly follow the docs.
=> chore: update readme for pointing latest network installation

.github/workflows/ci.yml, .github/workflows/refresh-manifests.yml
Closes https://github.com/FuelLabs/fuel.nix/issues/106
=> Use macos-latest-xlarge instead of self-hosted runners

.github/workflows/refresh-manifests.yml
beta-4-rc is not in the `milestones.nix`, which might be why this CI step is failing.
Also, beta-5 was missing here.
=> Replace beta-4-rc with beta-4 and beta-5 in CI

.github/workflows/ci.yml, .github/workflows/refresh-manifests.yml
CI has been failing for over a month. We shouldn't wait for users to report a problem. This will proactively notify slack.
=> Notify on slack when CI fails

.github/workflows/ci.yml, .github/workflows/refresh-manifests.yml, book/src/contributing/internals.md, book/src/contributing/internals/providing-milestones.md, book/src/packages.md, book/src/quick-start.md, flake.nix, milestones.nix
These toolchains are pretty much nonfunctional as there is no client endpoint anymore, and there’s no reason for anyone to use these.
=> Remove support for beta-1 beta-2 and beta-3

.github/workflows/refresh-manifests.yml
The download-manifests-and-nix-build action has been [failing](https://github.com/FuelLabs/fuel.nix/actions/runs/8311430669/job/22745959329#logs) with running out of memory using ubuntu-latest. This switches to using to buildjet-4vcpu-ubuntu-2204.
=> use buildjet-4vcpu-ubuntu-2204 instead of ubuntu-latest

.github/workflows/refresh-manifests.yml
This PR addresses the CI job failure when there are no changes to commit by checking for changes before attempting a commit. This change ensures the job exits gracefully in such cases, preventing unnecessary failures.
You can see what was previously happening in this situation [here](https://github.com/FuelLabs/fuel.nix/actions/runs/8413088073)
=> Fix CI Failure on No Changes to Commit

patches.nix
fuel-core requires wasm32 rust toolchain and our CI was blocked because of this requirement. This PR adds wasm32 target after 2024-04-13
=> fix: add wasm32 target for fuel-core after 2024-04-13

manifests/forc-0.54.0-nightly-2024-04-14.nix, manifests/forc-0.54.0-nightly-2024-04-16.nix, manifests/forc-0.54.0-nightly-2024-04-17.nix, manifests/forc-client-0.54.0-nightly-2024-04-14.nix, manifests/forc-client-0.54.0-nightly-2024-04-16.nix, manifests/forc-client-0.54.0-nightly-2024-04-17.nix, manifests/forc-doc-0.54.0-nightly-2024-04-14.nix, manifests/forc-doc-0.54.0-nightly-2024-04-16.nix, manifests/forc-doc-0.54.0-nightly-2024-04-17.nix, manifests/forc-fmt-0.54.0-nightly-2024-04-14.nix, manifests/forc-fmt-0.54.0-nightly-2024-04-16.nix, manifests/forc-fmt-0.54.0-nightly-2024-04-17.nix, manifests/forc-lsp-0.54.0-nightly-2024-04-14.nix, manifests/forc-lsp-0.54.0-nightly-2024-04-16.nix, manifests/forc-lsp-0.54.0-nightly-2024-04-17.nix, manifests/forc-tx-0.54.0-nightly-2024-04-14.nix, manifests/forc-tx-0.54.0-nightly-2024-04-16.nix, manifests/forc-tx-0.54.0-nightly-2024-04-17.nix, manifests/fuel-core-0.24.2-nightly-2024-04-16.nix, manifests/fuel-core-0.24.2-nightly-2024-04-17.nix, manifests/fuel-core-client-0.24.2-nightly-2024-04-16.nix, manifests/fuel-core-client-0.24.2-nightly-2024-04-17.nix
Follow up to https://github.com/FuelLabs/fuel.nix/pull/133
=> chore: Refresh manifests after wasm patch

patches.nix
`forc-crypto` & `forc-debug` were added in #138 but the refresh manifests are [failing](https://github.com/FuelLabs/fuel.nix/actions/runs/9727826909/job/26848946788)
I think this is because I forgot to add them to the patches.nix file in the forc-plugins list. Hopefully this is all that's needed but we'll see once this is merged and the refresh manifests job is run again.
=> add missing packages to forc-plugins list

book/src/contributing/adding-packages.md, book/src/packages.md, filters.nix, flake.nix, manifests/forc-explore-0.0.0-nightly-2022-09-01.nix, manifests/forc-explore-0.0.0-nightly-2022-10-06.nix, manifests/forc-explore-0.0.0-nightly-2022-10-27.nix, manifests/forc-explore-0.0.0-nightly-2022-10-28.nix, manifests/forc-explore-0.28.1.nix, milestones.nix, script/refresh-manifests.sh
[forc-explorer](https://github.com/FuelLabs/forc-explorer) has been archived so we are removing it from fuel.nix.
=> remove forc explore

manifests/forc-wallet-0.8.2-nightly-2024-07-11.nix, manifests/forc-wallet-0.8.2-nightly-2024-08-13.nix, manifests/forc-wallet-0.9.0.nix, patches.nix
https://github.com/FuelLabs/fuel.nix/actions/runs/10361272047/job/28683384240
```
forc-wallet> error: package `fuels v0.66.0` cannot be built because it requires rustc 1.79.0 or newer, while the currently active rustc version is 1.76.0
```
=> chore: patch rust v1.79.0

.github/workflows/patch-pr.yml, flake.lock, manifests/forc-0.62.0-nightly-2024-08-15.nix, manifests/forc-client-0.62.0-nightly-2024-08-15.nix, manifests/forc-crypto-0.62.0-nightly-2024-08-15.nix, manifests/forc-debug-0.62.0-nightly-2024-08-15.nix, manifests/forc-doc-0.62.0-nightly-2024-08-15.nix, manifests/forc-fmt-0.62.0-nightly-2024-08-15.nix, manifests/forc-lsp-0.62.0-nightly-2024-08-15.nix, manifests/forc-tx-0.62.0-nightly-2024-08-15.nix, manifests/fuel-core-0.32.1-nightly-2024-08-15.nix, manifests/fuel-core-client-0.32.1-nightly-2024-08-15.nix, patches.nix
Running `nix flake update` in CI before refreshing the manifests.
Related https://github.com/oxalica/rust-overlay/issues/185
=> ci: Run nix flake update

book/src/nix-setup.md, book/src/quick-start.md
I had permission trouble ("unable to create symlink: permission denied", etc.) with `nix-installer` v0.9.0 (Macbook M3 Pro, MacOS Sonoma 14.6.1) as provided by the docs, so I used one of the latest stable releases.
This update might make (re-)installation of Nix via our docs more stable for Mac users.
I opted for v0.20.2, which fixes lots of bugs since v0.9.0, and also adds support for MacOS 15 beta, which might be useful soon (v0.21.0 adds extra features that are irrelevant for us now, so I went with a month-older release).
We should either:
- update the version of `nix-installer` more often (preferred, I think; v0.9.0 was released in May 2023, more than a year ago!)
- use `install.determinate.systems/nix` without a `tag` to get the latest stable release of `nix-installer`, but that …
=> docs(nix-setup): update nix-installer to v0.20.2

milestones.nix
Updates testnet channel to use:
fuel-core 0.35.0
forc 0.63.5
forc-wallet 0.9.0
This is sourced from the fuelup toolchain file [here](https://raw.githubusercontent.com/FuelLabs/fuelup/gh-pages/channel-fuel-testnet.toml)
=> chore: bump testnet versions

milestones.nix
Pins testnet forc version to 0.65.2 tag.
=> feat: bump forc version to 0.65.2 in test-net

.github/workflows/ci.yml, .github/workflows/refresh-manifests.yml, milestones.nix
Adds new milestones for mainnet and ignition. For now they are the same milestone, following the design in fuelup.
=> feat: add mainnet and ignition milestones

milestones.nix
- chore: bump mainnet & testnet channel - forc-wallet v0.11.1
=> chore: bump mainnet & testnet channel - forc-wallet 0.11.1

.github/workflows/patch-pr.yml, manifests/forc-0.48.1-nightly-2024-01-01.nix, manifests/forc-client-0.48.1-nightly-2024-01-01.nix, manifests/forc-crypto-0.48.1-nightly-2024-01-01.nix, manifests/forc-debug-0.48.1-nightly-2024-01-01.nix, manifests/forc-doc-0.48.1-nightly-2024-01-01.nix, manifests/forc-fmt-0.48.1-nightly-2024-01-01.nix, manifests/forc-lsp-0.48.1-nightly-2024-01-01.nix, manifests/forc-tx-0.48.1-nightly-2024-01-01.nix, manifests/forc-wallet-0.4.0-nightly-2024-01-01.nix, manifests/fuel-core-0.22.0-nightly-2024-01-01.nix, manifests/fuel-core-client-0.22.0-nightly-2024-01-01.nix, patches.nix, script/refresh-manifests.sh
Makes it so only nightlies after 01-01-2024 receive new patches. This cuts the time to refresh manifests down from ~3 hours to [43 min](https://github.com/FuelLabs/fuel.nix/actions/runs/12659594373)
=> Update nightly date for manifest refresh

.github/workflows/patch-pr.yml, .github/workflows/refresh-manifests.yml
Switch to using GitHub's built-in GITHUB_TOKEN instead of our custom REPO_TOKEN in CI workflows.
=> chore: migrate from REPO_TOKEN to GITHUB_TOKEN

.github/workflows/refresh-manifests.yml
It's failing due to missing permissions: https://github.com/FuelLabs/fuel.nix/actions/runs/12919430407
Testing it here: https://github.com/FuelLabs/fuel.nix/actions/runs/12937628058
=> ci: add permissions for github token refresh-manifests

.github/workflows/ci.yml
closes #158.
Adds a CI job to assert nix-shell works as described in the quick start.
=> ci: add a ci job to ensure quick start works

flake.nix
closes #166.
Removes the auto hardening enabled on nixOS to fix the build fail in debug mode for fuel repos. More details about the issue and root cause can be found in the issue ticker.
=> fix: tikv-jmalloc fails to build in debug mode by disabling hardening in fuel-dev shell

milestones.nix
bumps mainnet, testnet and devnet to use 
sway 0.67.0
forc-wallet 0.12.0
fuel-core 0.41.9
=> chore: bump networks to match fuelup versions

flake.lock, manifests/fuel-core-0.43.0-nightly-2025-04-12.nix, manifests/fuel-core-client-0.43.0-nightly-2025-04-12.nix, patches.nix
Bumps rust version for https://github.com/FuelLabs/fuel-core/commit/2a7e031fca28c751215030f719c99cb6a82d30f3
=> chore: use rust 1.85 as of 2025-04-10 for fuel-core

milestones.nix
bumps testnet to:
fuel-core: 0.43.1
forc-wallet: 0.14.0
sway: 0.68.1
=> chore: bump testnet channel versions

.github/workflows/update-milestones.yml, ci/update-milestones/src/main.rs
This pull request introduces updates to the GitHub Actions workflow for milestone updates and improves the formatting of the pull request description in the Rust codebase.
The changes enhance branch handling, commit behavior, and description clarity.
* **Branch handling improvements**: Updated the branch creation logic to check if the branch already exists remotely. If it does, the workflow fetches and checks out the existing branch instead of creating a new one.
* **Commit and push behavior**: Changed the commit message to follow a more descriptive convention (`chore: update milestones`) and added `--force-with-lease` to the push command to handle existing branches gracefully.
* **Milestones file argument**: Added a `--milestones-file` argument to the script to specify the …
=> bugfix: gh-action milestones.nix

.github/workflows/ci.yml, .github/workflows/patch-pr.yml, .github/workflows/publish-book.yml, .github/workflows/refresh-manifests.yml, .github/workflows/update-milestones.yml
BuildJet runners (v2.326.0) don't support node24 which actions/checkout@v5 requires. Downgrading to v4 which uses node20 resolves the refresh-manifests job failures.
=> ci: downgrade actions/checkout from v5 to v4 for BuildJet compatibility

script/refresh-manifests.sh
This date was [previously updated](https://github.com/FuelLabs/fuel.nix/pull/155) earlier this year, but I think we should bump it again as the refresh manifest job is taking a seriously long time again and there's no need to rebuild from this date.
=> chore: update nightly manifest cutoff date to 2025-04-01

script/refresh-manifests.sh
This was accidentally left over and should have been removed in the previous PR. it's the reason CI is [failing](https://github.com/FuelLabs/fuel.nix/actions/runs/18114347081/job/51552855943)
=> Remove the refresh call for `pkg_forc_node`
